export const CART_ACTION = {
  CART_ADD_ITEM: "CART_ADD_ITEM",
  CART_REMOVE_ITEM: " CART_REMOVE_ITEM",
  CART_SAVE_SHIPPPING_ADDRESS: "CART_SAVE_SHIPPPING_ADDRESS",
  CART_SAVE_PAYMENT_METHOD: "CART_SAVE_PAYMENT_METHOD",
};
