export const ORDER_ACTIONS = {
  ORDER_CREATE_REQUEST: "ORDER_CREATE_REQUEST",
  ORDER_CREATE_SUCCESS: "ORDER_CREATE_SUCCESS",
  ORDER_CREATE_FAIL: "ORDER_CREATE_FAIL",
};
export const ORDER_DETAILS_ACTIONS = {
  ORDER_DETAILS_REQUEST: "ORDER_DETAILS_REQUEST",
  ORDER_DETAILS_SUCCESS: "ORDER_DETAILS_SUCCESS",
  ORDER_DETAILS_FAIL: "ORDER_DETAILS_FAIL",
};
export const ORDER_PAY_ACTIONS = {
  ORDER_PAY_REQUEST: "ORDER_PAY_REQUEST",
  ORDER_PAY_SUCCESS: "ORDER_PAY_SUCCESS",
  ORDER_PAY_FAIL: "ORDER_PAY_FAIL",
  ORDER_PAY_RESET: "ORDER_PAY_RESET ",
};
export const ORDER_LIST_ACTIONS = {
  ORDER_LIST_MY_REQUEST: "ORDER_LIST_MY_REQUEST",
  ORDER_LIST_MY_SUCCESS: "ORDER_LIST_MY_SUCCESS",
  ORDER_LIST_MY_FAIL: "ORDER_LIST_MY_FAIL",
  ORDER_LIST_MY_RESET: "ORDER_LIST_MY_RESET",
};
export const ORDERS_LIST_ACTIONS = {
  ORDERS_LIST_REQUEST: "ORDERS_LIST_REQUEST",
  ORDERS_LIST_SUCCESS: "ORDERS_LIST_SUCCESS",
  ORDERS_LIST_FAIL: "ORDERS_LIST_FAIL",
  ORDERS_LIST_RESET: "ORDERS_LIST_RESET",
};
export const ORDERS_DELIVER_ACTIONS = {
  ORDERS_DELIVER_REQUEST: "ORDERS_DELIVER_REQUEST",
  ORDERS_DELIVER_SUCCESS: "ORDERS_DELIVER_SUCCESS",
  ORDERS_DELIVER_FAIL: "ORDERS_DELIVER_FAIL",
  ORDERS_DELIVER_RESET: "ORDERS_DELIVER_RESET",
};