export const ACTIONS = {
  PRODUCT_LIST_REQUEST: "PRODUCT_LIST_REQUEST",
  PRODUCT_LIST_SUCCESS: "PRODUCT_LIST_SUCCESS",
  PRODUCT_LIST_FAIL: "PRODUCT_LIST_FAIL",
};
export const DETAILS = {
  PRODUCT_DETAILS_IMPORT: "PRODUCT_DETAILS_IMPORT",
  PRODUCT_DETAILS_SUCCESS: "PRODUCT_DETAILS_SUCCESS",
  PRODUCT_DETAILS_FAIL: " PRODUCT_DETAILS_FAIL",
  PRODUCT_DETAILS_RESET: " PRODUCT_DETAILS_RESET",
};
export const DELETE_PRODUCTS = {
  PRODUCT_DELETE_REQUEST: "PRODUCT_DELETE_REQUEST",
  PRODUCT_DELETE_SUCCESS: "PRODUCT_DELETE_SUCCESS",
  PRODUCT_DELETE_FAIL: " PRODUCT_DELETE_FAIL",
};
export const CREATE_PRODUCT = {
  PRODUCT_CREATE_REQUEST: "PRODUCT_CREATE_REQUEST",
  PRODUCT_CREATE_SUCCESS: "PRODUCT_CREATE_SUCCESS",
  PRODUCT_CREATE_FAIL: " PRODUCT_CREATE_FAIL",
  PRODUCT_CREATE_RESET: " PRODUCT_CREATE_RESET",
};
export const EDIT_PRODUCT = {
  PRODUCT_EDIT_REQUEST: "PRODUCT_EDIT_REQUEST",
  PRODUCT_EDIT_SUCCESS: "PRODUCT_EDIT_SUCCESS",
  PRODUCT_EDIT_FAIL: " PRODUCT_EDIT_FAIL",
  PRODUCT_EDIT_RESET: " PRODUCT_EDIT_RESET",
};
export const CREATE_REVIEW_PRODUCT = {
  CREATE_REVIEW_PRODUCT_REQUEST: "CREATE_REVIEW_PRODUCT_REQUEST",
  CREATE_REVIEW_PRODUCT_SUCCESS: "CREATE_REVIEW_PRODUCT_SUCCESS",
  CREATE_REVIEW_PRODUCT_FAIL: " CREATE_REVIEW_PRODUCT_FAIL",
  CREATE_REVIEW_PRODUCT_RESET: " CREATE_REVIEW_PRODUCT_RESET",
};
export const TOP_RATED_PRODUCTS = {
  TOP_RATED_PRODUCTS_REQUEST: "TOP_RATED_PRODUCTS_REQUEST",
  TOP_RATED_PRODUCTS_SUCCESS: "TOP_RATED_PRODUCTS_SUCCESS",
  TOP_RATED_PRODUCTS_FAIL: " TOP_RATED_PRODUCTS_FAIL",
};
