export const USER_LOGIN = {
  USER_LOGIN_REQUEST: "USER_LOGIN_REQUEST ",
  USER_LOGIN_SUCCESS: "USER_LOGIN_SUCCESS",
  USER_LOGIN_FAIL: "USER_LOGIN_FAIL",
};
export const USER_REGISTER = {
  USER_REGISTER_REQUEST: "USER_REGISTER_REQUEST ",
  USER_REGISTER_SUCCESS: "USER_REGISTER_SUCCESS",
  USER_REGISTER_FAIL: "USER_REGISTER_FAIL",
};
export const USER_DETAILS = {
  USER_DETAILS_REQUEST: "USER_DETAILS_REQUEST ",
  USER_DETAILS_SUCCESS: "USER_DETAILS_SUCCESS",
  USER_DETAILS_FAIL: "USER_DETAILS_FAIL",
  USER_DETAILS_RESET: "USER_DETAILS_RESET",
};
export const USER_UPDATE = {
  USER_UPDATE_PROFILE_REQUEST: "USER_UPDATE_PROFILE_REQUEST",
  USER_UPDATE_PROFILE_SUCCESS: "USER_UPDATE_PROFILE_SUCCESS ",
  USER_UPDATE_PROFILE_FAIL: "USER_UPDATE_PROFILE_FAIL",
  USER_UPDATE_PROFILE_RESET: "USER_UPDATE_PROFILE_RESET",
};
export const USERS_LIST = {
  USERS_LIST_REQUEST: "USERS_LIST_REQUEST",
  USERS_LIST_SUCCESS: "USERS_LIST_SUCCESS ",
  USERS_LIST_FAIL: "USERS_LIST_FAIL",
  USERS_LIST_RESET: "USERS_LIST_RESET",
};
export const USER_DELETE = {
  USER_DELETE_REQUEST: "USER_DELETE_REQUEST",
  USER_DELETE_SUCCESS: "USER_DELETE_SUCCESS ",
  USER_DELETE_FAIL: "USER_DELETE_FAIL",
}
export const USERS_UPDATE = {
  USERS_UPDATE_REQUEST: "USERS_UPDATE_REQUEST",
  USERS_UPDATE_SUCCESS: "USERS_UPDATE_SUCCESS ",
  USERS_UPDATE_FAIL: "USERS_UPDATE_FAIL",
  USERS_UPDATE_RESET: "USERS_UPDATE_RESET",
};
export const USER_LOGOUT = "USER_LOGOUT";
